name: package-validation
run-name: Package validation

on:
  push:
    branches: 
    - master
    - main
    
jobs:
  composer-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: composer validate --no-check-lock
